steps:
  - label: ":android: Build Debug APK"
    key: "build-apk"
    command: "./gradlew assembleDebug"
    artifact_paths: "app/build/outputs/apk/debug/app-debug.apk"
    agents:
      queue: local
      
  - label: ":package: Upload APK Info"
    command: |
      echo "✅ APK build complete!"
      ls -lh app/build/outputs/apk/debug/
    depends_on: "build-apk"
    agents:
      queue: local