steps:
  - label: "Run Unit Test"
    key: "unit-test"
    command: "./gradlew test"
    agents:
      queue: local
  
  - label: "Build Debug APK"
    key: "build-debug-apk"
    command: |
      ./gradlew assembleDebug
      cp app/build/outputs/apk/debug/app-debug.apk app-debug.apk
    agents:
      queue: local
    artifact_paths: "app-debug.apk"
    depends_on: "unit-test"